[package]
name = "area_calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.2.0"
cli-clipboard = "0.4.0"
eframe = "0.21"
egui-modal = "0.2.1"
tracing-subscriber = "0.3"
